apiVersion: v1
kind: Service
metadata:
  name: service-zuul
spec:
  ports:
    - protocol: TCP
      port: 8769
      targetPort: 8769
  selector:
    app: service-zuul
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-zuul
  labels:
    app: service-zuul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-zuul
  template:
    metadata:
      name: service-zuul
      labels:
        app: service-zuul
    spec:
      restartPolicy: Always
      containers:
        - name: service-zuul
          image: service-zuul:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8769
              name: server
          resources:
            limits:
              memory: 1000Mi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m
