apiVersion: v1
kind: Service
metadata:
  name: service-feign
spec:
  type: NodePort
  ports:
    - name: server
      nodePort: 31003
      port: 8765
      targetPort: 8765
  selector:
    app: service-feign
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-feign
  labels:
    app: service-feign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-feign
  template:
    metadata:
      name: service-feign
      labels:
        app: service-feign
    spec:
      restartPolicy: Always
      containers:
        - name: service-feign
          image: service-feign:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8765
              name: server
          resources:
            limits:
              memory: 1000Mi
              cpu: 1000m
            requests:
              memory: 500Mi
              cpu: 500m
