server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-hi/**
      url: http://service-hi:8762
    api-b:
      path: /api-feign/**
      url: http://service-feign:8765